# Generated by Django 2.0 on 2019-02-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Order'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress1',
            new_name='shoppingAddress1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingCity',
            new_name='shoppingCity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingCountry',
            new_name='shoppingCountry',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingName',
            new_name='shoppingName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPostcode',
            new_name='shoppingPostcode',
        ),
    ]
