# Generated by Django 2.0 on 2019-03-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190227_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shoppingAddress1',
            new_name='shippingAddress1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shoppingCity',
            new_name='shippingCity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shoppingCountry',
            new_name='shippingCountry',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shoppingName',
            new_name='shippingName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shoppingPostcode',
            new_name='shippingPostcode',
        ),
    ]
